List<Map<String, dynamic>> countryList = [
  {
    "country_en": "Afghanistan",
    "flag": "🇦🇫",
    "country_code": "AF",
    "phone_code": 93,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Åland Islands",
    "flag": "🇦🇽",
    "country_code": "AX",
    "phone_code": 358,
    "min_length": 6,
    "max_length": 9,
  },
  {
    "country_en": "Albania",
    "flag": "🇦🇱",
    "country_code": "AL",
    "phone_code": 355,
    "min_length": 8,
    "max_length": 9,
  },
  {
    "country_en": "Algeria",
    "flag": "🇩🇿",
    "country_code": "DZ",
    "phone_code": 213,
    "min_length": 8,
    "max_length": 9,
  },
  {
    "country_en": "American Samoa",
    "flag": "🇦🇸",
    "country_code": "AS",
    "phone_code": 1684,
    "min_length": 7,
    "max_length": 10,
  },
  {
    "country_en": "Andorra",
    "flag": "🇦🇩",
    "country_code": "AD",
    "phone_code": 376,
    "min_length": 6,
    "max_length": 9,
  },
  {
    "country_en": "Angola",
    "flag": "🇦🇴",
    "country_code": "AO",
    "phone_code": 244,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Anguilla",
    "flag": "🇦🇮",
    "country_code": "AI",
    "phone_code": 1264,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Antarctica",
    "flag": "🇦🇶",
    "country_code": "AQ",
    "phone_code": 672,
    "min_length": 6,
    "max_length": 9,
  },
  {
    "country_en": "Antigua and Barbuda",
    "flag": "🇦🇬",
    "country_code": "AG",
    "phone_code": 1268,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Argentina",
    "flag": "🇦🇷",
    "country_code": "AR",
    "phone_code": 54,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Armenia",
    "flag": "🇦🇲",
    "country_code": "AM",
    "phone_code": 374,
    "min_length": 6,
    "max_length": 8,
  },
  {
    "country_en": "Aruba",
    "flag": "🇦🇼",
    "country_code": "AW",
    "phone_code": 297,
    "min_length": 7,
    "max_length": 7,
  },
  {
    "country_en": "Australia",
    "flag": "🇦🇺",
    "country_code": "AU",
    "phone_code": 61,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Austria",
    "flag": "🇦🇹",
    "country_code": "AT",
    "phone_code": 43,
    "min_length": 7,
    "max_length": 13,
  },
  {
    "country_en": "Azerbaijan",
    "flag": "🇦🇿",
    "country_code": "AZ",
    "phone_code": 994,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Bahamas",
    "flag": "🇧🇸",
    "country_code": "BS",
    "phone_code": 1242,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Bahrain",
    "flag": "🇧🇭",
    "country_code": "BH",
    "phone_code": 973,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Bangladesh",
    "flag": "🇧🇩",
    "country_code": "BD",
    "phone_code": 880,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Barbados",
    "flag": "🇧🇧",
    "country_code": "BB",
    "phone_code": 1246,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Belarus",
    "flag": "🇧🇾",
    "country_code": "BY",
    "phone_code": 375,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Belgium",
    "flag": "🇧🇪",
    "country_code": "BE",
    "phone_code": 32,
    "min_length": 8,
    "max_length": 10,
  },
  {
    "country_en": "Belize",
    "flag": "🇧🇿",
    "country_code": "BZ",
    "phone_code": 501,
    "min_length": 7,
    "max_length": 7,
  },
  {
    "country_en": "Benin",
    "flag": "🇧🇯",
    "country_code": "BJ",
    "phone_code": 229,
    "min_length": 8,
    "max_length": 9,
  },
  {
    "country_en": "Bermuda",
    "flag": "🇧🇲",
    "country_code": "BM",
    "phone_code": 1441,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Bhutan",
    "flag": "🇧🇹",
    "country_code": "BT",
    "phone_code": 975,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Bolivia, Plurinational State of bolivia",
    "flag": "🇧🇴",
    "country_code": "BO",
    "phone_code": 591,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Bosnia and Herzegovina",
    "flag": "🇧🇦",
    "country_code": "BA",
    "phone_code": 387,
    "min_length": 8,
    "max_length": 9,
  },
  {
    "country_en": "Botswana",
    "flag": "🇧🇼",
    "country_code": "BW",
    "phone_code": 267,
    "min_length": 7,
    "max_length": 8,
  },
  {
    "country_en": "Bouvet Island",
    "flag": "🇧🇻",
    "country_code": "BV",
    "phone_code": 47,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Brazil",
    "flag": "🇧🇷",
    "country_code": "BR",
    "phone_code": 55,
    "min_length": 10,
    "max_length": 11,
  },
  {
    "country_en": "British Indian Ocean Territory",
    "flag": "🇮🇴",
    "country_code": "IO",
    "phone_code": 246,
    "min_length": 7,
    "max_length": 7,
  },
  {
    "country_en": "Brunei Darussalam",
    "flag": "🇧🇳",
    "country_code": "BN",
    "phone_code": 673,
    "min_length": 7,
    "max_length": 8,
  },
  {
    "country_en": "Bulgaria",
    "flag": "🇧🇬",
    "country_code": "BG",
    "phone_code": 359,
    "min_length": 9,
    "max_length": 10,
  },
  {
    "country_en": "Burkina Faso",
    "flag": "🇧🇫",
    "country_code": "BF",
    "phone_code": 226,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Burundi",
    "flag": "🇧🇮",
    "country_code": "BI",
    "phone_code": 257,
    "min_length": 8,
    "max_length": 9,
  },
  {
    "country_en": "Cambodia",
    "flag": "🇰🇭",
    "country_code": "KH",
    "phone_code": 855,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Cameroon",
    "flag": "🇨🇲",
    "country_code": "CM",
    "phone_code": 237,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Canada",
    "flag": "🇨🇦",
    "country_code": "CA",
    "phone_code": 1,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Cape Verde",
    "flag": "🇨🇻",
    "country_code": "CV",
    "phone_code": 238,
    "min_length": 7,
    "max_length": 7,
  },
  {
    "country_en": "Cayman Islands",
    "flag": "🇰🇾",
    "country_code": "KY",
    "phone_code": 1345,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Central African Republic",
    "flag": "🇨🇫",
    "country_code": "CF",
    "phone_code": 236,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Chad",
    "flag": "🇹🇩",
    "country_code": "TD",
    "phone_code": 235,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Chile",
    "flag": "🇨🇱",
    "country_code": "CL",
    "phone_code": 56,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "China",
    "flag": "🇨🇳",
    "country_code": "CN",
    "phone_code": 86,
    "min_length": 11,
    "max_length": 11,
  },
  {
    "country_en": "Christmas Island",
    "flag": "🇨🇽",
    "country_code": "CX",
    "phone_code": 61,
    "min_length": 8,
    "max_length": 9,
  },
  {
    "country_en": "Cocos (Keeling) Islands",
    "flag": "🇨🇨",
    "country_code": "CC",
    "phone_code": 61,
    "min_length": 8,
    "max_length": 9,
  },
  {
    "country_en": "Colombia",
    "flag": "🇨🇴",
    "country_code": "CO",
    "phone_code": 57,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Comoros",
    "flag": "🇰🇲",
    "country_code": "KM",
    "phone_code": 269,
    "min_length": 7,
    "max_length": 7,
  },
  {
    "country_en": "Congo",
    "flag": "🇨🇬",
    "country_code": "CG",
    "phone_code": 242,
    "min_length": 7,
    "max_length": 7,
  },
  {
    "country_en": "Congo, The Democratic Republic of the Congo",
    "flag": "🇨🇩",
    "country_code": "CD",
    "phone_code": 243,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Cook Islands",
    "flag": "🇨🇰",
    "country_code": "CK",
    "phone_code": 682,
    "min_length": 5,
    "max_length": 5,
  },
  {
    "country_en": "Costa Rica",
    "flag": "🇨🇷",
    "country_code": "CR",
    "phone_code": 506,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Côte d'Ivoire",
    "flag": "🇨🇮",
    "country_code": "CI",
    "phone_code": 225,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Croatia",
    "flag": "🇭🇷",
    "country_code": "HR",
    "phone_code": 385,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Cuba",
    "flag": "🇨🇺",
    "country_code": "CU",
    "phone_code": 53,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Cyprus",
    "flag": "🇨🇾",
    "country_code": "CY",
    "phone_code": 357,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Czech Republic",
    "flag": "🇨🇿",
    "country_code": "CZ",
    "phone_code": 420,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Denmark",
    "flag": "🇩🇰",
    "country_code": "DK",
    "phone_code": 45,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Djibouti",
    "flag": "🇩🇯",
    "country_code": "DJ",
    "phone_code": 253,
    "min_length": 6,
    "max_length": 6,
  },
  {
    "country_en": "Dominica",
    "flag": "🇩🇲",
    "country_code": "DM",
    "phone_code": 1767,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Dominican Republic",
    "flag": "🇩🇴",
    "country_code": "DO",
    "phone_code": 1829,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Ecuador",
    "flag": "🇪🇨",
    "country_code": "EC",
    "phone_code": 593,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Egypt",
    "flag": "🇪🇬",
    "country_code": "EG",
    "phone_code": 20,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "El Salvador",
    "flag": "🇸🇻",
    "country_code": "SV",
    "phone_code": 503,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Equatorial Guinea",
    "flag": "🇬🇶",
    "country_code": "GQ",
    "phone_code": 240,
    "min_length": 6,
    "max_length": 6,
  },
  {
    "country_en": "Eritrea",
    "flag": "🇪🇷",
    "country_code": "ER",
    "phone_code": 291,
    "min_length": 7,
    "max_length": 7,
  },
  {
    "country_en": "Estonia",
    "flag": "🇪🇪",
    "country_code": "EE",
    "phone_code": 372,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Ethiopia",
    "flag": "🇪🇹",
    "country_code": "ET",
    "phone_code": 251,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Falkland Islands (Malvinas)",
    "flag": "🇫🇰",
    "country_code": "FK",
    "phone_code": 500,
    "min_length": 5,
    "max_length": 5,
  },
  {
    "country_en": "Faroe Islands",
    "flag": "🇫🇴",
    "country_code": "FO",
    "phone_code": 298,
    "min_length": 5,
    "max_length": 5,
  },
  {
    "country_en": "Fiji",
    "flag": "🇫🇯",
    "country_code": "FJ",
    "phone_code": 679,
    "min_length": 7,
    "max_length": 7,
  },
  {
    "country_en": "Finland",
    "flag": "🇫🇮",
    "country_code": "FI",
    "phone_code": 358,
    "min_length": 8,
    "max_length": 10,
  },
  {
    "country_en": "France",
    "flag": "🇫🇷",
    "country_code": "FR",
    "phone_code": 33,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "French Guiana",
    "flag": "🇬🇫",
    "country_code": "GF",
    "phone_code": 594,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "French Polynesia",
    "flag": "🇵🇫",
    "country_code": "PF",
    "phone_code": 689,
    "min_length": 6,
    "max_length": 6,
  },
  {
    "country_en": "French Southern Territories",
    "flag": "🇹🇫",
    "country_code": "TF",
    "phone_code": 262,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Gabon",
    "flag": "🇬🇦",
    "country_code": "GA",
    "phone_code": 241,
    "min_length": 7,
    "max_length": 7,
  },
  {
    "country_en": "Gambia",
    "flag": "🇬🇲",
    "country_code": "GM",
    "phone_code": 220,
    "min_length": 7,
    "max_length": 7,
  },
  {
    "country_en": "Georgia",
    "flag": "🇬🇪",
    "country_code": "GE",
    "phone_code": 995,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Germany",
    "flag": "🇩🇪",
    "country_code": "DE",
    "phone_code": 49,
    "min_length": 10,
    "max_length": 11,
  },
  {
    "country_en": "Ghana",
    "flag": "🇬🇭",
    "country_code": "GH",
    "phone_code": 233,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Gibraltar",
    "flag": "🇬🇮",
    "country_code": "GI",
    "phone_code": 350,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Greece",
    "flag": "🇬🇷",
    "country_code": "GR",
    "phone_code": 30,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Greenland",
    "flag": "🇬🇱",
    "country_code": "GL",
    "phone_code": 299,
    "min_length": 6,
    "max_length": 6,
  },
  {
    "country_en": "Grenada",
    "flag": "🇬🇩",
    "country_code": "GD",
    "phone_code": 1473,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Guadeloupe",
    "flag": "🇬🇵",
    "country_code": "GP",
    "phone_code": 590,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Guam",
    "flag": "🇬🇺",
    "country_code": "GU",
    "phone_code": 1671,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Guatemala",
    "flag": "🇬🇹",
    "country_code": "GT",
    "phone_code": 502,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Guernsey",
    "flag": "🇬🇬",
    "country_code": "GG",
    "phone_code": 44,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Guinea",
    "flag": "🇬🇳",
    "country_code": "GN",
    "phone_code": 224,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Guinea-Bissau",
    "flag": "🇬🇼",
    "country_code": "GW",
    "phone_code": 245,
    "min_length": 7,
    "max_length": 7,
  },
  {
    "country_en": "Guyana",
    "flag": "🇬🇾",
    "country_code": "GY",
    "phone_code": 592,
    "min_length": 7,
    "max_length": 7,
  },
  {
    "country_en": "Haiti",
    "flag": "🇭🇹",
    "country_code": "HT",
    "phone_code": 509,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Heard Island and Mcdonald Islands",
    "flag": "🇭🇲",
    "country_code": "HM",
    "phone_code": 672,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Holy See (Vatican City State)",
    "flag": "🇻🇦",
    "country_code": "VA",
    "phone_code": 379,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Honduras",
    "flag": "🇭🇳",
    "country_code": "HN",
    "phone_code": 504,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Hong Kong",
    "flag": "🇭🇰",
    "country_code": "HK",
    "phone_code": 852,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Hungary",
    "flag": "🇭🇺",
    "country_code": "HU",
    "phone_code": 36,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Iceland",
    "flag": "🇮🇸",
    "country_code": "IS",
    "phone_code": 354,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "India",
    "flag": "🇮🇳",
    "country_code": "IN",
    "phone_code": 91,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Indonesia",
    "flag": "🇮🇩",
    "country_code": "ID",
    "phone_code": 62,
    "min_length": 9,
    "max_length": 11,
  },
  {
    "country_en": "Iran",
    "flag": "🇮🇷",
    "country_code": "IR",
    "phone_code": 98,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Iraq",
    "flag": "🇮🇶",
    "country_code": "IQ",
    "phone_code": 964,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Ireland",
    "flag": "🇮🇪",
    "country_code": "IE",
    "phone_code": 353,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Isle of Man",
    "flag": "🇮🇲",
    "country_code": "IM",
    "phone_code": 44,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Israel",
    "flag": "🇮🇱",
    "country_code": "IL",
    "phone_code": 972,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Italy",
    "flag": "🇮🇹",
    "country_code": "IT",
    "phone_code": 39,
    "min_length": 9,
    "max_length": 10,
  },
  {
    "country_en": "Jamaica",
    "flag": "🇯🇲",
    "country_code": "JM",
    "phone_code": 1876,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Japan",
    "flag": "🇯🇵",
    "country_code": "JP",
    "phone_code": 81,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Jersey",
    "flag": "🇯🇪",
    "country_code": "JE",
    "phone_code": 44,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Jordan",
    "flag": "🇯🇴",
    "country_code": "JO",
    "phone_code": 962,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Kazakhstan",
    "flag": "🇰🇿",
    "country_code": "KZ",
    "phone_code": 7,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Kenya",
    "flag": "🇰🇪",
    "country_code": "KE",
    "phone_code": 254,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Kiribati",
    "flag": "🇰🇮",
    "country_code": "KI",
    "phone_code": 686,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Korea, Democratic People's Republic of Korea",
    "flag": "🇰🇵",
    "country_code": "KP",
    "phone_code": 850,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Korea, Republic of South Korea",
    "flag": "🇰🇷",
    "country_code": "KR",
    "phone_code": 82,
    "min_length": 9,
    "max_length": 11,
  },
  {
    "country_en": "Kosovo",
    "flag": "🇽🇰",
    "country_code": "XK",
    "phone_code": 383,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Kuwait",
    "flag": "🇰🇼",
    "country_code": "KW",
    "phone_code": 965,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Kyrgyzstan",
    "flag": "🇰🇬",
    "country_code": "KG",
    "phone_code": 996,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Laos",
    "flag": "🇱🇦",
    "country_code": "LA",
    "phone_code": 856,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Latvia",
    "flag": "🇱🇻",
    "country_code": "LV",
    "phone_code": 371,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Lebanon",
    "flag": "🇱🇧",
    "country_code": "LB",
    "phone_code": 961,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Lesotho",
    "flag": "🇱🇸",
    "country_code": "LS",
    "phone_code": 266,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Liberia",
    "flag": "🇱🇷",
    "country_code": "LR",
    "phone_code": 231,
    "min_length": 7,
    "max_length": 8,
  },
  {
    "country_en": "Libyan Arab Jamahiriya",
    "flag": "🇱🇾",
    "country_code": "LY",
    "phone_code": 218,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Liechtenstein",
    "flag": "🇱🇮",
    "country_code": "LI",
    "phone_code": 423,
    "min_length": 7,
    "max_length": 7,
  },
  {
    "country_en": "Lithuania",
    "flag": "🇱🇹",
    "country_code": "LT",
    "phone_code": 370,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Luxembourg",
    "flag": "🇱🇺",
    "country_code": "LU",
    "phone_code": 352,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Macao",
    "flag": "🇲🇴",
    "country_code": "MO",
    "phone_code": 853,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Macedonia",
    "flag": "🇲🇰",
    "country_code": "MK",
    "phone_code": 389,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Madagascar",
    "flag": "🇲🇬",
    "country_code": "MG",
    "phone_code": 261,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Malawi",
    "flag": "🇲🇼",
    "country_code": "MW",
    "phone_code": 265,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Malaysia",
    "flag": "🇲🇾",
    "country_code": "MY",
    "phone_code": 60,
    "min_length": 7,
    "max_length": 7,
  },
  {
    "country_en": "Maldives",
    "flag": "🇲🇻",
    "country_code": "MV",
    "phone_code": 960,
    "min_length": 7,
    "max_length": 7,
  },
  {
    "country_en": "Mali",
    "flag": "🇲🇱",
    "country_code": "ML",
    "phone_code": 223,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Malta",
    "flag": "🇲🇹",
    "country_code": "MT",
    "phone_code": 356,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Marshall Islands",
    "flag": "🇲🇭",
    "country_code": "MH",
    "phone_code": 692,
    "min_length": 7,
    "max_length": 7,
  },
  {
    "country_en": "Martinique",
    "flag": "🇲🇶",
    "country_code": "MQ",
    "phone_code": 596,
    "min_length": 9,
    "max_length": 12,
  },
  {
    "country_en": "Mauritius",
    "flag": "🇲🇺",
    "country_code": "MU",
    "phone_code": 230,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Mayotte",
    "flag": "🇾🇹",
    "country_code": "YT",
    "phone_code": 262,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Mexico",
    "flag": "🇲🇽",
    "country_code": "MX",
    "phone_code": 52,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Micronesia, Federated States of Micronesia",
    "flag": "🇫🇲",
    "country_code": "FM",
    "phone_code": 691,
    "min_length": 7,
    "max_length": 7,
  },
  {
    "country_en": "Moldova",
    "flag": "🇲🇩",
    "country_code": "MD",
    "phone_code": 373,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Monaco",
    "flag": "🇲🇨",
    "country_code": "MC",
    "phone_code": 377,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Mongolia",
    "flag": "🇲🇳",
    "country_code": "MN",
    "phone_code": 976,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Montenegro",
    "flag": "🇲🇪",
    "country_code": "ME",
    "phone_code": 382,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Montserrat",
    "flag": "🇲🇸",
    "country_code": "MS",
    "phone_code": 1664,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Morocco",
    "flag": "🇲🇦",
    "country_code": "MA",
    "phone_code": 212,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Mozambique",
    "flag": "🇲🇿",
    "country_code": "MZ",
    "phone_code": 258,
    "min_length": 8,
    "max_length": 9,
  },
  {
    "country_en": "Myanmar",
    "flag": "🇲🇲",
    "country_code": "MM",
    "phone_code": 95,
    "min_length": 8,
    "max_length": 10,
  },
  {
    "country_en": "Namibia",
    "flag": "🇳🇦",
    "country_code": "NA",
    "phone_code": 264,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Nauru",
    "flag": "🇳🇷",
    "country_code": "NR",
    "phone_code": 674,
    "min_length": 7,
    "max_length": 7,
  },
  {
    "country_en": "Nepal",
    "flag": "🇳🇵",
    "country_code": "NP",
    "phone_code": 977,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Netherlands",
    "flag": "🇳🇱",
    "country_code": "NL",
    "phone_code": 31,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Netherlands Antilles",
    "flag": "",
    "country_code": "AN",
    "phone_code": 599,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "New Caledonia",
    "flag": "🇳🇨",
    "country_code": "NC",
    "phone_code": 687,
    "min_length": 6,
    "max_length": 6,
  },
  {
    "country_en": "New Zealand",
    "flag": "🇳🇿",
    "country_code": "NZ",
    "phone_code": 64,
    "min_length": 8,
    "max_length": 10,
  },
  {
    "country_en": "Nicaragua",
    "flag": "🇳🇮",
    "country_code": "NI",
    "phone_code": 505,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Niger",
    "flag": "🇳🇪",
    "country_code": "NE",
    "phone_code": 227,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Nigeria",
    "flag": "🇳🇬",
    "country_code": "NG",
    "phone_code": 234,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Niue",
    "flag": "🇳🇺",
    "country_code": "NU",
    "phone_code": 683,
    "min_length": 4,
    "max_length": 4,
  },
  {
    "country_en": "Norfolk Island",
    "flag": "🇳🇫",
    "country_code": "NF",
    "phone_code": 672,
    "min_length": 6,
    "max_length": 6,
  },
  {
    "country_en": "Northern Mariana Islands",
    "flag": "🇲🇵",
    "country_code": "MP",
    "phone_code": 1670,
    "min_length": 7,
    "max_length": 7,
  },
  {
    "country_en": "Norway",
    "flag": "🇳🇴",
    "country_code": "NO",
    "phone_code": 47,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Oman",
    "flag": "🇴🇲",
    "country_code": "OM",
    "phone_code": 968,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Pakistan",
    "flag": "🇵🇰",
    "country_code": "PK",
    "phone_code": 92,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Palau",
    "flag": "🇵🇼",
    "country_code": "PW",
    "phone_code": 680,
    "min_length": 7,
    "max_length": 7,
  },
  {
    "country_en": "Palestinian Territory, Occupied",
    "flag": "🇵🇸",
    "country_code": "PS",
    "phone_code": 970,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Panama",
    "flag": "🇵🇦",
    "country_code": "PA",
    "phone_code": 507,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Papua New Guinea",
    "flag": "🇵🇬",
    "country_code": "PG",
    "phone_code": 675,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Paraguay",
    "flag": "🇵🇾",
    "country_code": "PY",
    "phone_code": 595,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Peru",
    "flag": "🇵🇪",
    "country_code": "PE",
    "phone_code": 51,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Philippines",
    "flag": "🇵🇭",
    "country_code": "PH",
    "phone_code": 63,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Pitcairn",
    "flag": "🇵🇳",
    "country_code": "PN",
    "phone_code": 64,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Poland",
    "flag": "🇵🇱",
    "country_code": "PL",
    "phone_code": 48,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Portugal",
    "flag": "🇵🇹",
    "country_code": "PT",
    "phone_code": 351,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Puerto Rico",
    "flag": "🇵🇷",
    "country_code": "PR",
    "phone_code": 1939,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Qatar",
    "flag": "🇶🇦",
    "country_code": "QA",
    "phone_code": 974,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Romania",
    "flag": "🇷🇴",
    "country_code": "RO",
    "phone_code": 40,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Russia",
    "flag": "🇷🇺",
    "country_code": "RU",
    "phone_code": 7,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Rwanda",
    "flag": "🇷🇼",
    "country_code": "RW",
    "phone_code": 250,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Reunion",
    "flag": "🇷🇪",
    "country_code": "RE",
    "phone_code": 262,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Saint Barthelemy",
    "flag": "🇧🇱",
    "country_code": "BL",
    "phone_code": 590,
    "min_length": 6,
    "max_length": 6,
  },
  {
    "country_en": "Saint Helena, Ascension and Tristan Da Cunha",
    "flag": "🇸🇭",
    "country_code": "SH",
    "phone_code": 290,
    "min_length": 4,
    "max_length": 7,
  },
  {
    "country_en": "Saint Kitts and Nevis",
    "flag": "🇰🇳",
    "country_code": "KN",
    "phone_code": 1869,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Saint Lucia",
    "flag": "🇱🇨",
    "country_code": "LC",
    "phone_code": 1758,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Saint Martin",
    "flag": "🇲🇫",
    "country_code": "MF",
    "phone_code": 590,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Saint Pierre and Miquelon",
    "flag": "🇵🇲",
    "country_code": "PM",
    "phone_code": 508,
    "min_length": 6,
    "max_length": 6,
  },
  {
    "country_en": "Saint Vincent and the Grenadines",
    "flag": "🇻🇨",
    "country_code": "VC",
    "phone_code": 1784,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Samoa",
    "flag": "🇼🇸",
    "country_code": "WS",
    "phone_code": 685,
    "min_length": 5,
    "max_length": 7,
  },
  {
    "country_en": "San Marino",
    "flag": "🇸🇲",
    "country_code": "SM",
    "phone_code": 378,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Sao Tome and Principe",
    "flag": "🇸🇹",
    "country_code": "ST",
    "phone_code": 239,
    "min_length": 7,
    "max_length": 7,
  },
  {
    "country_en": "Saudi Arabia",
    "flag": "🇸🇦",
    "country_code": "SA",
    "phone_code": 966,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Senegal",
    "flag": "🇸🇳",
    "country_code": "SN",
    "phone_code": 221,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Serbia",
    "flag": "🇷🇸",
    "country_code": "RS",
    "phone_code": 381,
    "min_length": 8,
    "max_length": 9,
  },
  {
    "country_en": "Seychelles",
    "flag": "🇸🇨",
    "country_code": "SC",
    "phone_code": 248,
    "min_length": 7,
    "max_length": 7,
  },
  {
    "country_en": "Sierra Leone",
    "flag": "🇸🇱",
    "country_code": "SL",
    "phone_code": 232,
    "min_length": 6,
    "max_length": 6,
  },
  {
    "country_en": "Singapore",
    "flag": "🇸🇬",
    "country_code": "SG",
    "phone_code": 65,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Slovakia",
    "flag": "🇸🇰",
    "country_code": "SK",
    "phone_code": 421,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Slovenia",
    "flag": "🇸🇮",
    "country_code": "SI",
    "phone_code": 386,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Solomon Islands",
    "flag": "🇸🇧",
    "country_code": "SB",
    "phone_code": 677,
    "min_length": 7,
    "max_length": 7,
  },
  {
    "country_en": "Somalia",
    "flag": "🇸🇴",
    "country_code": "SO",
    "phone_code": 252,
    "min_length": 7,
    "max_length": 8,
  },
  {
    "country_en": "South Africa",
    "flag": "🇿🇦",
    "country_code": "ZA",
    "phone_code": 27,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "South Sudan",
    "flag": "🇸🇸",
    "country_code": "SS",
    "phone_code": 211,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "South Georgia and the South Sandwich Islands",
    "flag": "🇬🇸",
    "country_code": "GS",
    "phone_code": 500,
    "min_length": 6,
    "max_length": 9,
  },
  {
    "country_en": "Spain",
    "flag": "🇪🇸",
    "country_code": "ES",
    "phone_code": 34,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Sri Lanka",
    "flag": "🇱🇰",
    "country_code": "LK",
    "phone_code": 94,
    "min_length": 7,
    "max_length": 7,
  },
  {
    "country_en": "Sudan",
    "flag": "🇸🇩",
    "country_code": "SD",
    "phone_code": 249,
    "min_length": 7,
    "max_length": 7,
  },
  {
    "country_en": "Suriname",
    "flag": "🇸🇷",
    "country_code": "SR",
    "phone_code": 597,
    "min_length": 6,
    "max_length": 7,
  },
  {
    "country_en": "Svalbard and Jan Mayen",
    "flag": "🇸🇯",
    "country_code": "SJ",
    "phone_code": 47,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Eswatini",
    "flag": "🇸🇿",
    "country_code": "SZ",
    "phone_code": 268,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Sweden",
    "flag": "🇸🇪",
    "country_code": "SE",
    "phone_code": 46,
    "min_length": 7,
    "max_length": 10,
  },
  {
    "country_en": "Switzerland",
    "flag": "🇨🇭",
    "country_code": "CH",
    "phone_code": 41,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Syrian Arab Republic",
    "flag": "🇸🇾",
    "country_code": "SY",
    "phone_code": 963,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Taiwan",
    "flag": "🇹🇼",
    "country_code": "TW",
    "phone_code": 886,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Tajikistan",
    "flag": "🇹🇯",
    "country_code": "TJ",
    "phone_code": 992,
    "min_length": 4,
    "max_length": 9,
  },
  {
    "country_en": "Tanzania, United Republic of Tanzania",
    "flag": "🇹🇿",
    "country_code": "TZ",
    "phone_code": 255,
    "min_length": 6,
    "max_length": 6,
  },
  {
    "country_en": "Thailand",
    "flag": "🇹🇭",
    "country_code": "TH",
    "phone_code": 66,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Timor-Leste",
    "flag": "🇹🇱",
    "country_code": "TL",
    "phone_code": 670,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Togo",
    "flag": "🇹🇬",
    "country_code": "TG",
    "phone_code": 228,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Tokelau",
    "flag": "🇹🇰",
    "country_code": "TK",
    "phone_code": 690,
    "min_length": 4,
    "max_length": 5,
  },
  {
    "country_en": "Tonga",
    "flag": "🇹🇴",
    "country_code": "TO",
    "phone_code": 676,
    "min_length": 7,
    "max_length": 7,
  },
  {
    "country_en": "Trinidad and Tobago",
    "flag": "🇹🇹",
    "country_code": "TT",
    "phone_code": 1868,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Tunisia",
    "flag": "🇹🇳",
    "country_code": "TN",
    "phone_code": 216,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Turkey",
    "flag": "🇹🇷",
    "country_code": "TR",
    "phone_code": 90,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Turkmenistan",
    "flag": "🇹🇲",
    "country_code": "TM",
    "phone_code": 993,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Turks and Caicos Islands",
    "flag": "🇹🇨",
    "country_code": "TC",
    "phone_code": 1649,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Tuvalu",
    "flag": "🇹🇻",
    "country_code": "TV",
    "phone_code": 688,
    "min_length": 5,
    "max_length": 5,
  },
  {
    "country_en": "Uganda",
    "flag": "🇺🇬",
    "country_code": "UG",
    "phone_code": 256,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Ukraine",
    "flag": "🇺🇦",
    "country_code": "UA",
    "phone_code": 380,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "United Arab Emirates",
    "flag": "🇦🇪",
    "country_code": "AE",
    "phone_code": 971,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "United Kingdom",
    "flag": "🇬🇧",
    "country_code": "GB",
    "phone_code": 44,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "United States",
    "flag": "🇺🇸",
    "country_code": "US",
    "phone_code": 1,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Uruguay",
    "flag": "🇺🇾",
    "country_code": "UY",
    "phone_code": 598,
    "min_length": 8,
    "max_length": 8,
  },
  {
    "country_en": "Uzbekistan",
    "flag": "🇺🇿",
    "country_code": "UZ",
    "phone_code": 998,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Vanuatu",
    "flag": "🇻🇺",
    "country_code": "VU",
    "phone_code": 678,
    "min_length": 5,
    "max_length": 7,
  },
  {
    "country_en": "Venezuela, Bolivarian Republic of Venezuela",
    "flag": "🇻🇪",
    "country_code": "VE",
    "phone_code": 58,
    "min_length": 7,
    "max_length": 7,
  },
  {
    "country_en": "Vietnam",
    "flag": "🇻🇳",
    "country_code": "VN",
    "phone_code": 84,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Virgin Islands, British",
    "flag": "🇻🇬",
    "country_code": "VG",
    "phone_code": 1284,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Virgin Islands, U.S.",
    "flag": "🇻🇮",
    "country_code": "VI",
    "phone_code": 1340,
    "min_length": 10,
    "max_length": 10,
  },
  {
    "country_en": "Wallis and Futuna",
    "flag": "🇼🇫",
    "country_code": "WF",
    "phone_code": 681,
    "min_length": 4,
    "max_length": 6,
  },
  {
    "country_en": "Yemen",
    "flag": "🇾🇪",
    "country_code": "YE",
    "phone_code": 967,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Zambia",
    "flag": "🇿🇲",
    "country_code": "ZM",
    "phone_code": 260,
    "min_length": 9,
    "max_length": 9,
  },
  {
    "country_en": "Zimbabwe",
    "flag": "🇿🇼",
    "country_code": "ZW",
    "phone_code": 263,
    "min_length": 9,
    "max_length": 9,
  }
];
